### ISSUE TITLE
Chrome packaged app

### ISSUE THREAD

**Issue by THemming** [janodvarko/harviewer#10]
Thanks for creating this project, it's been a real help. I recently made use of this project, server-less so I changed index.php to be a plain html file. I needed to run it locally for company privacy reasons. It got me thinking that a packaged Chrome app would be great for business users.

Will you be interested in distributing as a Chrome packaged app on the Chrome store? If not then I'll probably do so, adhering to the BSD license of course. And I'll make the source for the additional packaging available through a GitHub repository.

**Comment by janodvarko** [comment]
Nice!

Honza
