### ISSUE TITLE
stable URL has been down for a few days now

### ISSUE THREAD

**Issue by alex1x** [janodvarko/harviewer#105]
stable URL has been down for a few days now

**Comment by gitgrimbo** [comment]
Thanks.

The http://gitgrimbo.github.io/harviewer/master/ URL should be ok.

@janodvarko, is your URL down temporarily?

**Comment by janodvarko** [comment]
Yes, sorry, someone hacked my site. I am just fixing it. Should be back online soon.

Jan Honza Odvarko

**Comment by janodvarko** [comment]
Back online again.
