### ISSUE TITLE
Viewer returns incorrect content

### ISSUE THREAD

**Issue by alex4200** [janodvarko/harviewer#109]
I have created a har file with firefox (58.0.2) and dropped it into the online mask. 

All I get was something like the following: 

![screen shot 2018-03-07 at 12 41 24](https://user-images.githubusercontent.com/12729291/37090547-14f66cae-2205-11e8-8d1c-ced7d224ba3d.png)

Maybe the format has been changed or something?

**Comment by janodvarko** [comment]
This is a bug in Firefox 
https://bugzilla.mozilla.org/show_bug.cgi?id=1441761

Honza

**Comment by janodvarko** [comment]
Fixed in Firefox 60
Honza
