### ISSUE TITLE
request incorrectly placed in the timeline, total load time affected

### ISSUE THREAD

**Issue by iovuio** [janodvarko/harviewer#12]
I have a har file with a request that has a start time of 20s, however it's displayed as if it started at 0s.
The total load time is shown as 7s, however I expect it to be 20+s because of the said request.
File available under https://gist.github.com/iovuio/73cf1a5f98dd4bed91f9
Thank you

**Comment by gitgrimbo** [comment]
Hi.  Is the gist link you provide a public one?  I can't view it.

**Comment by gitgrimbo** [comment]
Closing due to invalid/non-public gist link and lack of response.
