### ISSUE TITLE
Create firebug.next extension to visualize HAR file responses

### ISSUE THREAD

**Issue by cadorn** [janodvarko/harviewer#13]
Create an extension for firebug.next that loads the bundled viewer [1] and renders har files in the response preview panel.

The point is to validate the process of embedding/running this component into another application/container.

[1] - https://github.com/janodvarko/harviewer/pull/11

**Comment by cadorn** [comment]
I cannot assign to myself.

**Comment by gitgrimbo** [comment]
@cadorn, @janodvarko, is this issue still relevant?

**Comment by cadorn** [comment]
I am going to try and patch https://github.com/janodvarko/harviewer/pull/11 to make it work again. We can close this issue for now.

**Comment by gitgrimbo** [comment]
Thanks @cadorn.  I've been playing in my spare time with a webpack/React implementation of HAR Viewer.  It's early days but maybe this could also lead to easier bundling of HAR Viewer in other applications.

**Comment by cadorn** [comment]
@gitgrimbo My effort in this regard was to provide a demo for an advanced bundling system I am working on. I am using this harviewer as a test just like the ace editor.

Will be interesting to see which bundled harviewer is most compact and feature rich while being easily embeddable anywhere.
