### ISSUE TITLE
Cannot GET /

### ISSUE THREAD

**Issue by jish** [janodvarko/harviewer#138]
When I run `npm start` and open http://localhost:49001/ I see a message:

    Cannot GET /

I now know from reading the Readme that I was supposed to go to http://localhost:49001/webapp/ instead.

What do you think about adding a message at http://localhost:49001/ instructing the user to navigate to http://localhost:49001/webapp/ ?

**Comment by gitgrimbo** [comment]
Hi, good idea.

Is this change enough do you think?

https://github.com/gitgrimbo/harviewer/commit/81fe57b54a7beedb2fd2dba2c01b61dd1e829d16

**Comment by jish** [comment]
Thanks! 🙇
