### ISSUE TITLE
Total Page Load Time

### ISSUE THREAD

**Issue by yihuic** [janodvarko/harviewer#14]
So far we are using the starting time of the first request as a starting point. We may use the starting time of this page as a starting point instead. Otherwise, we will see some confused page load time in  har preview

**Comment by gitgrimbo** [comment]
Hi.  Is this an issue with the exported HAR data or with HAR Viewer?

From what I can see from HAR exports, for every page there will be an entry whose `entry.startedDateTime` matches `page.startedDateTime`.

For example:

    {
      "log":{
        ...
        "pages":[{
            "startedDateTime":"2010-01-02T14:51:01.186+01:00",
            "id":"page_62143",
            ...
          }
        ],
        "entries":[{
            "pageref":"page_62143",
            "startedDateTime":"2010-01-02T14:51:01.186+01:00",

**Comment by yihuic** [comment]
Hi,
From my observation, they do not match. For example:
    "pages" : [ {      "startedDateTime" : "2016-06-16T14:53:28.238-04:00",      "id" : "Logon",      "title" : "",      "pageTimings" : {        "comment" : ""      },      "comment" : ""    } ],    "entries" : [ {      "pageref" : "Logon",      "startedDateTime" : "2016-06-16T14:53:29.426-04:00",
Therefore, I think we can use the value of pages startedDateTime as the starting time.
Regards,Yihui
Date: Sat, 25 Jun 2016 11:40:49 -0700

**Comment by gitgrimbo** [comment]
Where does that HAR content come from?

**Comment by gitgrimbo** [comment]
Hi @yihuic, do you have a sample HAR file you can attach to this issue?

**Comment by gitgrimbo** [comment]
Closing as cannot replicate and further information has not been provided.
