### ISSUE TITLE
How to get compressed page size

### ISSUE THREAD

**Issue by syndy1989** [janodvarko/harviewer#144]
Hi,

I embedded har viewer in to my report. I'm able to take the uncompressed page size from har (log.entries.response.content.size). But i'm not sure how the compressed pagesize is being calculated in har viewer. Any advise on how to calculate compressed page size would be of great help. Thanks in advance.

**Comment by gitgrimbo** [comment]
Hi,

The transferred size of an entry (i.e. the number of bytes the entry requires over-the-wire, so this could be a gzip'ed size, for instance) should be `entry.response.bodySize`, but not all browsers treat this property in the same way.

So in theory the compressed size of a page would be the sum of all its compressed entries.

HAR Viewer uses this code to get transferred entry sizes:

https://github.com/janodvarko/harviewer/blob/93726fa0791fad432203205da8c0555d6cf81795/webapp/scripts/preview/harModel.js#L386-L397

**Comment by syndy1989** [comment]
It worked. Thankyou @gitgrimbo
