### ISSUE TITLE
uBlock (and other adblockers) blocks harviewer by default

### ISSUE THREAD

**Issue by kmike** [janodvarko/harviewer#15]
Hey @janodvarko,

Could you please rename https://github.com/janodvarko/harviewer/blob/master/webapp/scripts/tabs/pageStats.js file? There is a rule to block "PageStats." files in EasyPrivacy list, and "pageStats.js" matches this pattern. uBlock uses EasyPrivacy list by default, and other ad blockers may use it.

Originally found in https://github.com/scrapinghub/splash/issues/163. Thanks for the awesome HAR viewer! We're using it in https://github.com/scrapinghub/splash, and it helps a lot with debugging.

**Comment by janodvarko** [comment]
But the file isn't there if you build the final package for distribution, no?

Honza

**Comment by kmike** [comment]
Hm, yes, this is not a problem when all JS code is combined. But I'm not using a build step: harviewer is included as a submodule and its static files are served as-is.

**Comment by janodvarko** [comment]
I see, makes sense. Can you send PR?

Honza

**Comment by kmike** [comment]
This is fixed by #53.
