### ISSUE TITLE
Ability to customize Har Viewer Statistic Pie charts colors and tooltips specified with title attribute of the HTML elements

### ISSUE THREAD

**Issue by jyiwong** [janodvarko/harviewer#19]
Hi, 
I am exploring the Har Viewer latest version 2.0.16 with the goal to incorporate it into our own web page. Would like to re-theme the colors and styles to our own. I am able to override some of the colors and styles with our own CSS,  but found the following issues:
1.  The Statistic Pie charts colors are hard coded in scripts/tabs/pageStats.js file.  Is there any way to override these colors without changing/editing the scripts/tabs/pageStats.js file directly?  I have studied the code and it seems to be impossible since the all the Pie chart objects (such as TimingPie, contentPie, TrafficPie and CachePie are buried in the function scope of pageStats.js which are not exposed. As an enhancement for the future releases, it will be nice to expose the setting of the Pie chart object colors, so application can customize the Pie charts color easily.
2. The tooltips of the Page Timeline bars and pie charts are implemented with the 'title' attribute of the HTML element, which makes hard to customize the background color of the tooltips since the background color of the title tooltips are depending on the OS setting. Again, to make customization possible, it would be nice to have the title tooltips implemented as other  tooltips implemented for the waiting bar in the page list with the .infoTip class. 
3. Is there any plan to upgrade require.js from version 0.24.0 (which is 4 years old) to the latest version? 

Thanks,
JC

**Comment by janodvarko** [comment]
All three points sounds good to me (mainly the require.js update).

Are you interested to provide a patch?

Honza

**Comment by gitgrimbo** [comment]
Closed by #103
