### ISSUE TITLE
Create Event is not supported in IE8

### ISSUE THREAD

**Issue by janodvarko** [janodvarko/harviewer#2]
Reported by Daniel

b.fireEvent=function(a,b){if(document.createEvent){var c=document.createEvent("Events");c.initEvent(b,!0,!1);return!a.dispatchEvent(c)}}

to

b.fireEvent=function(a,b){if(document.createEvent){var c=document.createEvent("Events");c.initEvent(b,!0,!1);return!a.dispatchEvent(c)}else if(document.createEventObject){$(a).trigger(b);}}

Waiting for a pull request

Honza

**Comment by gitgrimbo** [comment]
Hi @janodvarko, can this be closed?

[jQuery 2 does not support IE8](https://blog.jquery.com/2013/04/18/jquery-2-0-released/) and #30 was an upgrade to jQuery 2.

**Comment by janodvarko** [comment]
Yes, I think we can close this one.

Honza
