### ISSUE TITLE
'undefined' tab displayed for HAR output generated by Firefox

### ISSUE THREAD

**Issue by SebastianZ** [janodvarko/harviewer#21]
With [bug 859058](https://bugzilla.mozilla.org/show_bug.cgi?id=859058) being implemented, it's now possible to save or copy the network requests from within the Firefox DevTools.

Though importing the generated HAR causes a tab named *undefined* to be displayed besides the *Headers* tab for all requests.

Sebastian

**Comment by janodvarko** [comment]
Yes, I've seen this. Do you know what's causing it?
Honza

**Comment by SebastianZ** [comment]
Not yet, but I'll investigate it.

Sebastian

**Comment by SebastianZ** [comment]
The empty `postData` is causing this:

    "postData": {
      "mimeType": "",
      "params": [],
      "text": ""
    },

See also [bug 1174095](https://bugzilla.mozilla.org/show_bug.cgi?id=1174095).

Sebastian

**Comment by gitgrimbo** [comment]
Hi.  When I paste the following content into harviewer (it has `postData` in the same format as above), I don't see the issue.  Am I looking in the wrong place?

Copy and paste the content from:

https://gist.githubusercontent.com/gitgrimbo/7017186f3e2c5ea8280b/raw/503d757f50e52c353c5bf41e487be2e4586acc87/empty-postData.jsonp

Into:

http://www.softwareishard.com/har/viewer/
