### ISSUE TITLE
Charset in MIME type causes content preview to fail

### ISSUE THREAD

**Issue by SebastianZ** [janodvarko/harviewer#22]
[According to the HAR spec](http://www.softwareishard.com/blog/har-12-spec/#content), the charset should be included if it is available:

> mimeType [string] - MIME type of the response text (value of the Content-Type response header). The charset attribute of the MIME type is included (if available).

Though if the `mimeType` field of the response contains a charset, e.g. like `text/html; charset=UTF-8`, the preview tab (in this case *HTML*) is not displayed.

Sebastian

**Comment by gitgrimbo** [comment]
Hi, can you confirm with this URL?

http://www.softwareishard.com/har/viewer/?path=examples/google.com.har

The first item for "`www.google.cz`" has response header "`Content-Type: text/html; charset=UTF-8`".

Clicking this item shows the HTML tab is displayed, and the HTML preview inside this tab is displayed.

![harviewer-22](https://cloud.githubusercontent.com/assets/1020541/8971437/6ad2dd7a-3648-11e5-82b4-e23d13e15114.png)

**NOTE** - This is with Firefox 39.  IE 11 also works.  But Chrome (44) shows the HTML tab, but no HTML preview.  A quick look at why suggests the IFRAME onload event is handled differently in Chrome to the other two browsers mentioned.

Can you confirm the browser you are using?

**Comment by SebastianZ** [comment]
Note that the HAR of the example URL has `mimeType` set to `text/html`, not `text/html; charset=UTF-8`. So it is working.

Try this example instead:
https://gist.github.com/SebastianZ/d4e2f29090f65e504e8a

FWIW I am using Windows 7 + Firefox 39.0. Please note that I updated [the bug description](https://github.com/janodvarko/harviewer/issues/22#issue-87696413).

Sebastian

**Comment by gitgrimbo** [comment]
Ah yes, I see what you mean.  Should be a quick fix here to remove the charset from `repsonse.content.mimeType` before comparison:

https://github.com/janodvarko/harviewer/blob/master/webapp/scripts/preview/requestBody.js#L94

````
    showHtml: function(file)
    {
        return (file.response.content.mimeType == "text/html") ||
            (file.mimeType == "application/xhtml+xml");
    },
````

**Comment by janodvarko** [comment]
Fixed, thanks for the pointer.

Honza

**Comment by SebastianZ** [comment]
@janodvarko When do you plan to upload the changes?

Sebastian

**Comment by janodvarko** [comment]
Soon

Honza
