### ISSUE TITLE
Images are not displayed

### ISSUE THREAD

**Issue by SebastianZ** [janodvarko/harviewer#23]
The *Response* tab should display a preview of an image. Instead it shows the encoded text saved within the HAR.

![Incorrect display of image preview](https://cloud.githubusercontent.com/assets/958943/8129090/d4389d4e-1105-11e5-9844-664d1db69bdb.png)

Sebastian

**Comment by gitgrimbo** [comment]
Hi, could you check out this branch pls, http://gitgrimbo.github.io/harviewer/issue-23/.

It should have image preview for

- images decoded from the content data in the HAR itself (if base64 encoded), and
- images with a simple `src` attribute pointing to the resource URL.

**Comment by SebastianZ** [comment]
Looks good to me. You should create a PR, so Honza can merge your changes.

Sebastian

**Comment by janodvarko** [comment]
@gitgrimbo just go ahead and commit, great job as usual!

Honza
