### ISSUE TITLE
Toolbar isn't fixed at the top

### ISSUE THREAD

**Issue by SebastianZ** [janodvarko/harviewer#24]
The toolbar containing the _Show Page Timeline_, _Show Statistics_, _Clear_ and download options is not fixed at the top. This means when scrolling down the page they are not displayed anymore.

![Toolbar not fixed at top](https://cloud.githubusercontent.com/assets/958943/8129159/83d39664-1106-11e5-8269-d50af844eff2.png)

**Comment by gitgrimbo** [comment]
I think HAR Viewer is meant to behave this way. Closing for this reason, and because this is very old issue.  If this is important, please raise the issue again.

**Comment by SebastianZ** [comment]
> I think HAR Viewer is meant to behave this way.

Why do you think so? Those options are global, so they should be always available.

>  If this is important, please raise the issue again.

Done that in #143 and described the reason behind that in more detail.

Sebastian
