### ISSUE TITLE
Use feature detection for text selection rather than IE userAgent test

### ISSUE THREAD

**Issue by gitgrimbo** [janodvarko/harviewer#25]
The new [/tests/functional/testSearchJsonQuery.js](https://github.com/janodvarko/harviewer/blob/838c0f65434cb1b27e3994358b5b4c8891fcf5b8/tests/functional/testSearchJsonQuery.js) test fails for IE9, but IE9 supports the necessary DOM APIs for this test to pass.

Perhaps use feature detection for this test, rather than regex testing `navigator.userAgent`.

**Aside** - Is there a minimum browser requirement for harviewer?  E.g. IE9 and above?

Using feature detection would require a couple of changes.

1) [/webapp/scripts/tabs/domTab.js](https://github.com/janodvarko/harviewer/blob/838c0f65434cb1b27e3994358b5b4c8891fcf5b8/webapp/scripts/tabs/domTab.js#L87)

Change

````
        // Lib.selectElementText doesn't support IE.
        if (Lib.isIE)
        {
            ...
        }
````

to

````
        // Lib.selectElementText doesn't support IE8 and below.
        if (!Lib.supportsSelectElementText)
````

2) [/webapp/scripts/core/lib.js](https://github.com/janodvarko/harviewer/blob/838c0f65434cb1b27e3994358b5b4c8891fcf5b8/webapp/scripts/core/lib.js)

Add

````
Lib.supportsSelectElementText = (window.getSelection && window.document.createRange) || (window.document.body.createTextRange);
````

**Comment by janodvarko** [comment]
> Aside - Is there a minimum browser requirement for harviewer? E.g. IE9 and above?

No

Honza
