### ISSUE TITLE
Build warning/error on mac (10.7.4)

### ISSUE THREAD

**Issue by jbroberg** [janodvarko/harviewer#3]
When running "ant build" the following error comes up in the ant output:

requirejs-unix:
     [exec] 
     [exec] Tracing dependencies for: harViewer
     [exec] 
     [exec] Tracing dependencies for: harPreview
     [exec] Uglifying file: /Users/brobergj/github/local/harviewer/webapp/scripts/../../webapp-build/har.js
     [exec] Uglifying file: /Users/brobergj/github/local/harviewer/webapp/scripts/../../webapp-build/scripts/app.build.js
     [exec] Cannot uglify file: /Users/brobergj/github/local/harviewer/webapp/scripts/../../webapp-build/scripts/app.build.js. Skipping it. Error is:
     [exec] Unexpected token: punc (:) (line: 0, col: 21, pos: 21)

**Comment by gitgrimbo** [comment]
Hi @jbroberg, is this still an issue for you or can you close it?

You might like to try a build again as there have been many changes to the ant script and harviewer code since July 2012.

Thanks.

**Comment by gitgrimbo** [comment]
Closing because it's the issue's 4th birthday and the build system has been significantly updated since 2012.

:birthday: :gift: :balloon: :tada: :cocktail: :cookie: :ice_cream: :icecream:
