### ISSUE TITLE
inputURL through hash instead of query string?

### ISSUE THREAD

**Issue by rolodato** [janodvarko/harviewer#31]
Would it be possible to support passing `inputURL` through the hash fragment instead of the query string? That way clients can be certain that any files passed through can't be read by the server.

Let me know if this is something you'd like to see added, and I can look into sending a PR.

**Comment by janodvarko** [comment]
The pull has been merged.

Just to make sure, the previous way (passing inputURL through the query string) still works, right?

Honza

**Comment by rolodato** [comment]
Yes, it still works fine. Only thing I haven't implemented is passing an arbitrary callback name through hash parameter, but it should be trivial if anyone wants to do it. Thanks for merging!

**Comment by janodvarko** [comment]
Excellent!

(and yes, wait if anyone needs that custom name)

Honza

**Comment by rolodato** [comment]
By the way, do you know if this update could be deployed to http://www.softwareishard.com/har/viewer/ ?

**Comment by janodvarko** [comment]
Ay, yes, I'll do it next week.

Honza

**Comment by rolodato** [comment]
@janodvarko any luck deploying the update? Let me know if I can help.
