### ISSUE TITLE
"Validate data before processing" and "Table View" checkbox bug

### ISSUE THREAD

**Issue by gitgrimbo** [janodvarko/harviewer#44]
Since the upgrade to jQuery (from 1.5.1 to 2.1.4), we should be using `prop("checked")` rather than `attr("checked")` for checkboxes.  See http://blog.jquery.com/2011/05/12/jquery-1-6-1-released/ for change.

Affects:

- "Validate data before processing?" checkbox on homeTab.
- "Table View" checkbox on domTab.

**Comment by janodvarko** [comment]
So, I guess this has been fixed by:
https://github.com/janodvarko/harviewer/commit/90ec59c0b78d18ece2e21b036b427b3bf0aef75a

Honza

**Comment by gitgrimbo** [comment]
Yeah, sorry I forgot to add a reference to the issue from the PR.  Cheers!

**Comment by janodvarko** [comment]
Not a problem, thanks for the patch!

Honza
