### ISSUE TITLE
Cached resources not shown for Chrome exports

### ISSUE THREAD

**Issue by nicobo** [janodvarko/harviewer#54]
It seems that HTTP 200/304 cached resources are not shown in the statistics graphs : even though they are noted "from cache" in Chromium's console during the navigation, the last graph always show 100% of "not cached" resources.

With Firefox I've a correct graph (so it's probably not a problem with HarViewer).

Are you aware of this limitation ?
Am I missing something ?

I am using the Chrome app to load exported har.
I've not gathered more data yet but I could it requested.

**Comment by gitgrimbo** [comment]
Hi.  Issue #61 had similar cache issues and so a branch was deployed to the following address:

http://gitgrimbo.github.io/harviewer/issue-61/

Can you see if this solves your issue?

**Comment by gitgrimbo** [comment]
Fixed by #85.
