### ISSUE TITLE
Firefox Error: Script error for: tabs/pageStats

### ISSUE THREAD

**Issue by mo0feng** [janodvarko/harviewer#55]
I encountered the following error in the Firefox 44.02 browser :

``
Error: Script error for: tabs/pageStats
http://requirejs.org/docs/errors.html#scripterror
	
var e = new Error(msg +'\nhttp://requirejs.org/docs/errors.html#' + id);
``
I use iframe customized.
$("#content").bind("onViewerPreInit", function (event) {})

**Comment by gitgrimbo** [comment]
Is this a duplicate of #53 (*Rename pageStats to harStats so uBlock doesn't block it*) or a separate issue?  Need more info I think.

**Comment by mo0feng** [comment]
@gitgrimbo The project is not in my hand now, so sorry.

**Comment by janodvarko** [comment]
> @gitgrimbo The project is not in my hand now, so sorry.

Do you mean that you don't have access to it or time to work on it?
(of course, I can fix the first one :-) )

Honza
