### ISSUE TITLE
mimeType is validated despite "Http-304 Not Modified"

### ISSUE THREAD

**Issue by vinaybond** [janodvarko/harviewer#56]
I have har file which has 304 not modified calls. Since HTTP-304 does not return any content, it does not have content/mime type. When I open the har file in har viewer, it gives me error like below and does not load the har file

Here is the error message:
log.entries[33].response.content.mimeType is missing and it is not optional

Mime-type validation should not be there for HTTP-304 request types.

-Vinay

**Comment by vinaybond** [comment]
Are we going to fix this. I guess this is a genuine issue.

**Comment by gitgrimbo** [comment]
Hi, how was your HAR file created?

The following link to harviewer uses an `inputUrl` parameter pointing to a HAR that has HTTP 304 responses in it and works fine.  The HAR was created by browsing harviewer itself and using "*Copy all as HAR*" from Chrome 50 dev tools.

http://www.softwareishard.com/har/viewer/?inputUrl=https://rawgit.com/gitgrimbo/2173aaab1a12efe9233323078d6e7c97/raw/a2db9c09af9a4479c1b05306d655228dcaf072a7/harviewer-56-har-with-304.harp.js

E.g. `trace.js` is a HTTP 304.  Its content is:

          "content": {
            "size": 531,
            "mimeType": "application/x-javascript"
          },

The headers for this resource in Chrome are as follows:

    HTTP/1.1 304 Not Modified
    Date: Tue, 24 May 2016 21:11:35 GMT
    Server: Apache
    Connection: Keep-Alive
    Keep-Alive: timeout=5, max=48
    ETag: "18a733d-213-52e937b2a6740"
    Expires: Tue, 24 May 2016 21:12:05 GMT
    Cache-Control: max-age=30

So this could be an issue with how your HAR has been created - that method of creation might not set the `mimeType` property.

This is the Gist of the HAR file.

https://gist.github.com/gitgrimbo/2173aaab1a12efe9233323078d6e7c97#file-harviewer-56-har-with-304-harp-js

**Comment by gitgrimbo** [comment]
The `content.mimeType` property is not optional according to the spec

http://www.softwareishard.com/blog/har-12-spec/#content

From what I can see, Fiddler 4.4.9.8, IE 11, Chrome 37 and Firefox/netExport all populate the `content.mimeType` property when the response is a HTTP 304.

Can you provide instructions as to how to recreate a HAR that is missing this property?

**Comment by gitgrimbo** [comment]
Hi @vinaybond, can you add any more details to this issue?

**Comment by vinaybond** [comment]
Hi,
Sorry I missed it last time so I could not replay. I am creating HAR file via BrowserMob Proxy (along with RobotFramework + Selenium WebDriver).

**Comment by gitgrimbo** [comment]
Can you attach an example HAR for inspection please? Preferably as small as possible but still highlighting the issue, thanks.

**Comment by vinaybond** [comment]
Here is the sample file. 


[TestPeople.zip](https://github.com/janodvarko/harviewer/files/356527/TestPeople.zip)

**Comment by gitgrimbo** [comment]
Thanks.

Just looking at the BrowserMob Proxy source code, it looks like this is the code that handles the `response.content.mimeType` field.

https://github.com/lightbody/browsermob-proxy/commit/d250e2a47b6f6660bc1903e73e44e973360e542e

So the field can be set to `null` in some situations.  I wonder if it's because BrowserMob Proxy is not a caching proxy - so it doesn't have this information available when it's forwarding a HTTP 304 back to the client.

@janodvarko, do you have any opinion here?  BrowserMob Proxy seems to be technically incompatible with the HAR spec, http://www.softwareishard.com/blog/har-12-spec/#content, but I'm not sure what else it can do if it doesn't have this information available (like a browser would).

**Comment by gitgrimbo** [comment]
@vinaybond - you can still load your HARs when you turn validation off though?

![](https://cloud.githubusercontent.com/assets/1020541/16351459/b9a6dc0c-3a5d-11e6-99a2-cd3895ee989d.png)

**Comment by vinaybond** [comment]
It worked when I remove the validation. Thank you very much. Really appreciated your help.


-Vinay

**Comment by gitgrimbo** [comment]
After I load your test HAR, there's still an error when you try to click on one of those entries, such as

- http://192.168.1.5/production_content_server/employeePicture/notdc000000000201236_employeePicture.JPEG

Given the `response.content.mimeType` field is mandatory according to the spec, there is code in HAR Viewer that assumes it is present and valid.  It might make sense to make this code more forgiving of the actual HAR content.
