### ISSUE TITLE
Internet Explorer don't load 2.0.17 webapp (addEventListener not available)

### ISSUE THREAD

**Issue by bigrck64** [janodvarko/harviewer#59]
I have deployed a copy of HarViewer 2.0.17 on my local server.
I only keep the "css" and "scripts" folder of the webapp project, and everything is working well on Firefox and Chrome.

However, with Internet Explorer 10 or 11, I can't start the webapp.
IE's console is showing the following problems.

![prtscr capture_3](https://cloud.githubusercontent.com/assets/9383270/14253482/efa7e63c-fa8b-11e5-8325-013eed980146.png)

jquery.js is basically telling that "addEventListener" is not available.
I find this very strange because IE don't have any problem to load the webapp version at http://www.softwareishard.com/har/viewer/

Do you have any idea why IE fail to load local copy of HarViewer webapp ?
Thanks !

**Comment by gitgrimbo** [comment]
IE10 using IE8 emulation mode will fail with the following error.  Are you using any kind of emulation mode or non-standards mode?

````
SCRIPT438: Object doesn't support property or method 'addEventListener'
File: jquery.js, Line: 26, Column: 41197
````

**Comment by bigrck64** [comment]
Damn you were right !
I don't know why, but my browser was in "Quirks IE5" for Document model.
Thanks for the good idea gitgrimbo !

![image](https://cloud.githubusercontent.com/assets/9383270/14284622/94325b1c-fb48-11e5-8fb0-79e5389b8f7e.png)
