### ISSUE TITLE
Adding the "serverIPAddress" and "connection" as extra columns ? (preview panel)

### ISSUE THREAD

**Issue by bigrck64** [janodvarko/harviewer#60]
Hello !

The HAR format already have the "serverIPAddress" (ip) and "connection" (port) into his JSON structure:
![prtscr capture_3](https://cloud.githubusercontent.com/assets/9383270/14345806/5e063a46-fcaf-11e5-8cbc-107c117e181c.png)

And at the moment, HARViewer can already display two extra columns: "Type" and "Domain"
![prtscr capture_2](https://cloud.githubusercontent.com/assets/9383270/14345747/0c26284e-fcaf-11e5-9f80-b8072be3767b.png)

Would it be difficult to add the "Server IP" and "Server Port" as more extra columns ?
I see that these entries are already declared into the \preview\harSchema.js file, but I don't know how to go further :)

Thanks for any tips !

**Comment by janodvarko** [comment]
This should be relatively strightforward. See this file:
https://github.com/janodvarko/harviewer/blob/master/webapp/scripts/preview/requestList.js
... and follow the same way used for the other columns.

Thew new columns you are suggesting should be hidden by default I believe.
Send PR and I'll review it.

Honza

**Comment by gitgrimbo** [comment]
Hi Jan, can you also take a look at #46 at the same time pls.  Thanks!

**Comment by bigrck64** [comment]
Thanks for giving tips about good direction, I will made a PR if I'm able to produce something that works :)
