### ISSUE TITLE
Java build broken?

### ISSUE THREAD

**Issue by gitgrimbo** [janodvarko/harviewer#69]
*The default build for harviewer, `ant build`, uses Node.JS.  This is the preferred way to build harviewer.  But the following issue suggests that the Java-based build is now broken.*

-----

Just tried `ant -Drjs.runner=java build` and it hangs for me.  I waited about 20 seconds and it was stuck here:

     [java] Tracing dependencies for: harViewer
     [java]
     [java] Tracing dependencies for: harPreview
     [java] Uglify file: D:/dev/git_repos/harviewer2/webapp-build/har.js

Running [jvisualvm](http://docs.oracle.com/javase/6/docs/technotes/guides/visualvm/applications_local.html) I could attach to the `org.mozilla.javascript.tools.shell.Main` code and saw this:

![harviewer-57-jvisualvm](https://cloud.githubusercontent.com/assets/1020541/15686411/0fc1a06c-2768-11e6-96c6-e1c59455f1a1.png)

so a lot of time is being burnt up in the [r.js](https://github.com/requirejs/r.js) code (top row in the Hot Spots).

The CPU is 100% (for a single core) and the build seems to have entered an infinite loop.

-----

- edit - Is the build hanging or running slowly? - https://github.com/mishoo/UglifyJS2/pull/1024

**Comment by gitgrimbo** [comment]
Tried to follow the [r.js Nashorn instructions](https://github.com/requirejs/r.js/commit/1271aa77232ba0b5e64d3c114a88a6b0a91dfc9a) by changing the `rjs-java` task to the following:

    <target name="rjs-java" depends="rjs-determine-runner, build-started" if="rjs.runner.isJava">
        <exec dir="${app.dir}/scripts" executable="jjs" resolveexecutable="true">
            <arg value="-scripting"/>
            <arg value="${rjs.cmd}"/>
            <arg value="--"/>
            <arg value="-o"/>
            <arg value="app.build.js"/>
        </exec>
    </target>

The build now succeeds, but is **much** slower than the Node.JS build.

`ant -Drjs.runner=java build`  (i.e. using `jjs`)

    BUILD SUCCESSFUL
    Total time: 1 minute 30 seconds

`ant build`  (i.e. using Node.JS)

    BUILD SUCCESSFUL
    Total time: 9 seconds

The slow Java build could be because I am not passing any optimising hints/arguments to `jjs`.  But for now this looks like a reasonable fix.

**Comment by dannydong** [comment]
@gitgrimbo, I failed at running: ant -Drjs.runner=java build due to I/O Error as below:
D:\Software\test_tool\Web\harviewer-master\harviewer-master>ant -Drjs.runner=java build
Buildfile: D:\Software\test_tool\Web\harviewer-master\harviewer-master\build.xml

check-rjs-folder:

get-rjs:

rjs-determine-runner:

rjs-java:
     [java] js: "D:\Software\test_tool\Web\harviewer-master\harviewer-master/r.js/dist/r.js", line 1
3991: unterminated string literal
     [java] js:         expression: "[AST_Node] the `switch` 鈥渄iscriminant鈥?
     [java] js: ...........................................................^
     [java] Java Result: 3

rjs-node:

build:
     [echo] Building HAR Viewer on:
     [echo] os.name = Windows 7
     [echo] os.arch = amd64
     [echo] os.version = 6.1
     [copy] Copying 1 file to D:\Software\test_tool\Web\harviewer-master\harviewer-master\webapp-bui
ld\scripts\preview
     [copy] Copying 1 file to D:\Software\test_tool\Web\harviewer-master\harviewer-master\webapp-bui
ld\scripts\domplate
    [jsmin] Minimizing D:\Software\test_tool\Web\harviewer-master\harviewer-master\webapp-build\scri
pts\domplate\domplate.js

BUILD FAILED
D:\Software\test_tool\Web\harviewer-master\harviewer-master\build.xml:186: I/O Error when preprocess
ing file

Total time: 3 seconds

**Comment by gitgrimbo** [comment]
What is 鈥渄iscriminant鈥?  Is this a new file in a modified version of harviewer?

Can you try building the standard harviewer package and see if that works, to rule out a more general issue?

**Comment by dannydong** [comment]
it's standard harviewer package, I looked into the line of build.xml, it shows:
        expression: "[AST_Node] the `switch` “discriminant”"
but don't know why it shows like that during building: expression: "[AST_Node] the switch 鈥渄iscriminant鈥?

**Comment by gitgrimbo** [comment]
Which line of [build.xml](https://github.com/janodvarko/harviewer/blob/780d9da416174d024fac9184351e4ba8718dd1e4/build.xml) shows '_expression: "[AST_Node] the switch “discriminant”_'?  As far as I can see this file has no such text.

Can you try deleting the `r.js.zip` file and `r.js` folder?  Maybe you have an old copy of `r.js`.  The build should bring in a new copy of `r.js` if this file and folder are deleted first.

[This line of uglifyjs](https://github.com/requirejs/r.js/blob/fe3d3211d2cd0371fe249a0d0217023899a4a2ea/build/jslib/uglifyjs.js#L775) which is in the r.js build folder looks like the text you see:

    expression: "[AST_Node] the `switch` “discriminant”"

But I can't reproduce this, sorry.

**Comment by gitgrimbo** [comment]
To get the Java (not Node.js, not Nashorn/jjs) build working, you may need to change the optimizer to closure.

Change [line 11 in app.build.js](https://github.com/janodvarko/harviewer/blob/0997957b3ecb9fbdb27df4260d5bc85c653fac81/webapp/scripts/app.build.js#L11) to 

     optimize: "closure",
