### ISSUE TITLE
feature request: pure har json load when inputUrl is CORS supported resource

### ISSUE THREAD

**Issue by c0b** [janodvarko/harviewer#87]
like I've collected some har files and saved on amazon s3, with proper CORS set, these pure json data can be loaded by any cross-domain script to load, including http://www.softwareishard.com/har/viewer/; or I can set CORS to allow read from www.softwareishard.com domain only; however it's not supported by current har-viewer, trying to load like this ends up showing a `load` in the text box

http://www.softwareishard.com/har/viewer/?inputUrl=https://s3.amazonaws.com/path/to/.../raw-har

although it's documented if the inputUrl put the json data enclosed by a callback function and makes it JSONP data, that would require a wrapper to load s3 resource and enclose it with the callback function, that should be a good workaround; but I believe if the har-viewer can load CORS resources and direct load with storage services like S3 that would be more flexible and release more possibilities...

**Comment by gitgrimbo** [comment]
Hi, this should already work using the `path` URL parameter.  For example, the following URLs both work for me:

1. [http://harviewer:49002/webapp/?path=http://harviewer:49001/selenium/tests/hars/issue-23/images.har](#)
2. [http://www.softwareishard.com/har/viewer/?path=http://harviewer:49001/selenium/tests/hars/issue-23/images.har](#)

[1] - ports are different so this is treated as cross-origin.
[1] and [2] - I have a CORS filter enabled on the 49001 server which sends the appropriate `Access-Control-Allow-Origin` header.

I think the docs for the `path` and `inputUrl` could be improved.  And maybe the URL parameters should be renamed to `har` and `harp`.

Please try this and confirm that it works/doesn't work for you.

**Comment by c0b** [comment]
indeed that `path` parameter works; and I don't see it's documented anywhere on the page
http://www.softwareishard.com/har/viewer/ so the docs definitely need improvement.

> `renamed to har and harp`

you may add want to add `har` as alias to `path` and `harp` alias `inputUrl`; don't remove `inputUrl` right away as it breaks people's url, but instead in docs mark it as deprecated.

**Comment by gitgrimbo** [comment]
Yep, I agree an alias sounds the best idea.  I'll take a look.

**Comment by gitgrimbo** [comment]
Hi, I've pushed a branch here, http://gitgrimbo.github.io/harviewer/x-alias-for-path-and-inputurl.

It passes all the tests, but if you could kick the tyres I'd appreciate it.

- `har` alias for `path`
- `harp` alias for `inputUrl`

**Comment by gitgrimbo** [comment]
Hi @c0b, did you get chance to take a look at the branch?  Does it suit your preferred use of `har` and `harp` parameter names?

**Comment by c0b** [comment]
@gitgrimbo I can verify that one works; use har & harp is more accurate, while path and inputUrl can be kept there for places where such urls already shared

http://gitgrimbo.github.io/harviewer/x-alias-for-path-and-inputurl/?har=http://har-on-my-local-server

**Comment by gitgrimbo** [comment]
Great.  Yep, the idea is to keep backwards compatibility with the old param names.

This new branch (note the extra "-2"), http://gitgrimbo.github.io/harviewer/x-alias-for-path-and-inputurl-2, also has an updated **About** tab that attempts to document the URL parameters.

For instance, the new `har` and `harp` parameters can be used together in the same URL, whereas you could only use one of either `path` or `inputUrl` before.

**Comment by gitgrimbo** [comment]
Closed by #93.
