### ISSUE TITLE
Now working embed mode.

### ISSUE THREAD

**Issue by msjuck** [janodvarko/harviewer#95]
this is html code.

> <!DOCTYPE

 html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <link rel="stylesheet" href="assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="assets/css/Mockup-MacBook-Pro.css">
    <link rel="stylesheet" href="assets/css/user.css">
    <link rel="stylesheet" href="assets/bootstrap/fonts/font-awesome.min.css">
    <script id="har" src="http://localhost/har.js"></script>
</head>

<body>
    <nav class="navbar navbar-default">
        <div class="container">

    <section class="testimonials">
        <div class="container">
            <div class="col-md-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title">Resent analytics report</h3>
                    </div>
                    <div class="panel-body"><span><div id="now_time"> 16-01-29 05:34:30</div></span>
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>Target Web site</th>
                                        <th>Status </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>ytn.co.kr.harp
                                            <p>2016-09-19_05_44_38</p>
                                        </td>
                                        <td>
                                            <div height=300 class="har" data-har="http://file.teemo.io/2016-09-19_05_44_55@google.com.harp"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>naver.com.harp
                                            <p>2016-09-19_05_44_48</p>
                                        </td>
                                        <td>
                                            <div height=300 class="har" data-har="http://file.teemo.io/2016-09-19_05_44_55@google.com.harp"></div>
                                        </td>
                                    </tr>
                                    <tr>
                                        <td>google.com.harp
                                            <p>2016-09-19_05_44_55</p>
                                        </td>
                                        <td>
                                            <div height=300 class="har" data-har="http://file.teemo.io/2016-09-19_05_44_55@google.com.harp"></div>
                                        </td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div></div>
            </div>
        </div>
    </section>
    <section class="features">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <h2>Useful Tools</h2>
                    <p>Morbi non mauris massa. Duis elit mauris, malesuada nec suscipit ac, bibendum sed augue. Maecenas condimentum magna gravida, laoreet nunc sed, euismod sem. </p>
                </div>
                <div class="col-md-6">
                    <div class="row icon-features">
                        <div class="col-xs-4 icon-feature"><span class="glyphicon glyphicon-cloud"></span>
                            <a href="http://isp.teemo.io?ip=150.123.123.123">
                                <p>ISP Checker</p>
                            </a>
                        </div>
                        <div class="col-xs-4 icon-feature"><span class="glyphicon glyphicon-map-marker"></span>
                            <p>GEO IP tracking</p>
                        </div>
                        <div class="col-xs-4 icon-feature"><span class="glyphicon glyphicon-floppy-save"></span>
                            <p>Report Export</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    <h5>Choi Hong Jun© 2016</h5>
                </div>
                <div class="col-sm-6 social-icons"><a href="#"><span class="fa fa-facebook"></span></a><a href="#"><span class="fa fa-twitter"></span></a><a href="#"><span class="fa fa-instagram"></span></a></div>
            </div>
        </div>
    </footer>
    <script src="assets/js/jquery.min.js"></script>
    <script src="assets/bootstrap/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        var currentdate = new Date();
        var datetime = "Updated: " + currentdate.getDate() + "/" + (currentdate.getMonth() + 1) + "/" + currentdate.getFullYear() + "  " + currentdate.getHours() + ":" + currentdate.getMinutes() + ":" + currentdate.getSeconds();
        document.getElementById("now_time").innerHTML = datetime;
    </script>
</body>

</html>

and the result is like this.

> 
log.entries[0].time	
 	number value found, but a integer is required
log.entries[0].timings.blocked	
 	number value found, but a integer is required
log.entries[0].timings.send	
 	number value found, but a integer is required
log.entries[0].timings.wait	
 	number value found, but a integer is required
log.entries[0].timings.receive	
 	number value found, but a integer is required
log.entries[1].time	
 	number value found, but a integer is required
log.entries[1].timings.blocked	
 	number value found, but a integer is required
log.entries[1].timings.send	
 	number value found, but a integer is required
log.entries[1].timings.wait	
 	number value found, but a integer is required
log.entries[1].timings.receive	
 	number value found, but a integer is required
log.entries[2].time	
 	number value found, but a integer is required
log.entries[2].timings.blocked	
 	number value found, but a integer is required
log.entries[2].timings.send	
 	number value found, but a integer is required
log.entries[2].timings.wait	
 	number value found, but a integer is required
log.entries[2].timings.receive	
 	number value found, but a integer is required
log.entries[3].time	
 	number value found, but a integer is required
log.entries[3].timings.blocked	
 	number value found, but a integer is required
log.entries[3].timings.send	
 	number value found, but a integer is required
log.entries[3].timings.wait	
 	number value found, but a integer is required
log.entries[3].timings.receive	
 	number value found, but a integer is required
log.entries[4].time	
 	number value found, but a integer is required
log.entries[4].timings.blocked	
 	number value found, but a integer is required
log.entries[4].timings.send	
 	number value found, but a integer is required
log.entries[4].timings.wait	
 	number value found, but a integer is required
log.entries[4].timings.receive	
 	number value found, but a integer is required
log.entries[5].time	
 	number value found, but a integer is required
log.entries[5].timings.blocked	
 	number value found, but a integer is required
log.entries[5].timings.send	
 	number value found, but a integer is required
log.entries[5].timings.wait	
 	number value found, but a integer is required
log.entries[5].timings.receive	
 	number value found, but a integer is required

**Comment by gitgrimbo** [comment]
Those are HAR validation errors.
- Are your HARs valid?
- What version of HAR Viewer are you using?
- Can you replicate the same errors by pasting one of your HAR files into the textarea here - http://gitgrimbo.github.io/harviewer/master/?

**Comment by gitgrimbo** [comment]
[This looks like the commit](https://github.com/janodvarko/harviewer/commit/d0a79dfd472a8904b008878b4c9f135badccbc6f) (from 14 Feb 2014) that changed the validation of those values from "integer" to "number".  So you are probably using an old version of HAR Viewer.

v2.0.17 was released on 21 March 2016, and an up-to-date master is available at http://gitgrimbo.github.io/harviewer/master/.

**Comment by msjuck** [comment]
Thank you gitgrimbo. I install my PC ( version 2.0.15 ) and I want to run on my PC

**Comment by msjuck** [comment]
it's ok on project website. but not on my pc.

**Comment by gitgrimbo** [comment]
v2.0.15 is from [13 Nov 2011](https://github.com/janodvarko/harviewer/commit/25b760f90e9011984e2f9a76864299ab2b8952c6).

That is a very old version.  I recommend you upgrade.

**Comment by msjuck** [comment]
gitgrimbo // Thank you so much. I just upgrade it ( unzip and copy to apache dir) but does not work...

**Comment by gitgrimbo** [comment]
What are the errors?

**Comment by msjuck** [comment]
i want embed on my index.html file. 

using 

>    <div height=300 class="har" data-har="http://file.teemo.io/2016-09-19_05_44_55@google.com.harp"></div>
                                    </td>


and this is error ( inside iframe )

> log.entries[0].time 
number value found, but a integer is required
log.entries[0].timings.blocked

number value found, but a integer is required
log.entries[0].timings.send 
number value found, but a integer is required
log.entries[0].timings.wait 
number value found, but a integer is required
log.entries[0].timings.receive

number value found, but a integer is required
log.entries[1].time 
number value found, but a integer is required
log.entries[1].timings.blocked

number value found, but a integer is required
log.entries[1].timings.send 
number value found, but a integer is required
log.entries[1].timings.wait 
number value found, but a integer is required
log.entries[1].timings.receive

number value found, but a integer is required
log.entries[2].time 
number value found, but a integer is required
log.entries[2].timings.blocked

number value found, but a integer is required
log.entries[2].timings.send 
number value found, but a integer is required
log.entries[2].timings.wait 
number value found, but a integer is required
log.entries[2].timings.receive

number value found, but a integer is required
log.entries[3].time 
number value found, but a integer is required
log.entries[3].timings.blocked

number value found, but a integer is required
log.entries[3].timings.send 
number value found, but a integer is required
log.entries[3].timings.wait 
number value found, but a integer is required
log.entries[3].timings.receive

number value found, but a integer is required
log.entries[4].time 
number value found, but a integer is required
log.entries[4].timings.blocked

number value found, but a integer is required
log.entries[4].timings.send 
number value found, but a integer is required
log.entries[4].timings.wait 
number value found, but a integer is required
log.entries[4].timings.receive

number value found, but a integer is required
log.entries[5].time 
number value found, but a integer is required
log.entries[5].timings.blocked

number value found, but a integer is required
log.entries[5].timings.send 
number value found, but a integer is required
log.entries[5].timings.wait 
number value found, but a integer is required
log.entries[5].timings.receive

number value found, but a integer is required

**Comment by gitgrimbo** [comment]
Those look like the same errors, and those errors shouldn't be output since the commit from 14 Feb 2014 that I mentioned.

**Comment by msjuck** [comment]
i change browser. i think it is not cache issue.

**Comment by msjuck** [comment]
Really big thank you. gitgrimbo. you are the best.

**Comment by gitgrimbo** [comment]
Glad it's working for you.  Is this issue resolved, can it be closed?

**Comment by msjuck** [comment]
not not clear but if you want to close, its okey. thank you
