### ISSUE TITLE
Unable to load local hars from the "file://" protocol

### ISSUE THREAD

**Issue by slipwalker** [janodvarko/harviewer#98]
I've got the error message in the Chrome console when trying to load har file to embedded HAR view:
 
_"XMLHttpRequest cannot load file:///tmp/myHar.har. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource."_

I hope that following manifest setting should solve this error:

`"chromium-args"` : `"--allow-file-access-from-files"`.

But actually, when trying the same in Firefox, it is loaded without error, but Iframe is empty (no har data present).

It would be very helpful to have possibility to load har file not only by http:// and others protocols but also by file://.

**Comment by gitgrimbo** [comment]
Hi,

HAR Viewer is a web app and not a Chrome extension, so there isn't a manifest, and the web app is subject to the usual browser security restrictions.

If HAR Viewer was turned into a Chrome extension then your suggestion would probably work, but that isn't something I've looked in to.

In the meantime, local files can be loaded by drag-and-dropping them onto the HAR Viewer web page.

Or you can spin up a local web server and serve your local HAR files yourself.  E.g. https://github.com/gitgrimbo/harviewer-screenshot, which shows these steps:

```
npm install -g http-server
cd FOLDER_CONTAINING_HARS
http-server --cors
```

Then you can address your HAR file from this local server.  E.g. if your server was http://localhost:8888/, then:

https://gitgrimbo.github.io/harviewer/master/?har=http://localhost:8888/my-har.har.

**Comment by slipwalker** [comment]
Thanks for the response. So, my local web server up and running now. I'm using HAR Preview Embedding mode. My html file looks like this:

`<!DOCTYPE HTML>`
``` 
<html>
<head>
   <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
   <script src="https://code.jquery.com/jquery-2.1.4.min.js" 
integrity="sha256-8WqyJLuWKRBVhxXIL1jBDD7SDxU936oZkCnxQbWwJVw=" crossorigin="anonymous">
   </script>
   <script id="har" type="text/javascript" src="http://www.softwareishard.com/har/viewer/har.js"></script>
</head>

<body>
<div class="har" data-har="http://localhost:8111/myHar.har" height="800px"></div>
</body>
</html>

```

But when the page is being opened, the following JS error is shown and data is not appears:

 `myHar.har?callback=onInputData&_=1484311914073:1 Uncaught SyntaxError: Unexpected token :`

**Comment by gitgrimbo** [comment]
I think the version of HAR Viewer at http://www.softwareishard.com expects a cross-domain HAR to be in the HARP format (similar to JSON/JSONP).

So your HAR file would have to be of the format:

`onInputData( ORIGINAL_HAR_FILE_CONTENTS_HERE )`

Maybe save your `myHar.har` as `myHar.harp`.  In `myHar.harp`, wrap the contents with `onInputData(` at the start of the file, and `)` at the end, and try `data-har="http://localhost:8111/myHar.harp"` in your HTML file.

**Comment by slipwalker** [comment]
Looks like it is not very convenient way for me. Would it be possible to make it working for _.har_ files as well?

**Comment by gitgrimbo** [comment]
I'll take a look, but in the meantime can you confirm that the steps above would work for you, even if it's not ideal for your situation?

**Comment by slipwalker** [comment]
Yeah, that workaround is working.

**Comment by gitgrimbo** [comment]
Cool.  The embedding side of things hasn't gotten much love recently.

I think it boils down to the embedding code using the old URL parameter names (`path` and `inputURL`), and making the assumption that only JSONP-type files can be loaded cross-domain.  With CORS this isn't true.

The new `har` and `harp` URL parameters are simply for the HAR (JSON) and HARP (JSONP) file formats respectively, and don't try to force HARP for cross-domain, as CORS+HAR works fine.

This sort of thing is discussed in #87, and I think the fix will be similar.

**Comment by gitgrimbo** [comment]
Hi @slipwalker,

I've pushed a version of the code to this URL, http://gitgrimbo.github.io/harviewer/issue-98/.

If this version works for you then I'll push to master.

Here are the edits for you to make to your original HTML file:
- Change the URL of `har.js`.
- Use one of the two new attributes, `data-har-url` and `data-harp-url`, depending on whether you want to load a HAR or HARP resource from the server.  Note that for HAR resources to be loaded cross-domain, you need to have CORS enabled on the server. #87 has more info about this.

```html
<script id="har" type="text/javascript"
    src="http://gitgrimbo.github.io/harviewer/issue-98/har.js"></script>
...
<div class="har" height="100px"
    data-har-url="http://harviewer2:49001/webapp/examples/inline-scripts-block.har"></div>
<div class="har" height="100px"
    data-harp-url="http://harviewer2:49001/webapp/examples/inline-scripts-block.harp"></div>
```
